config:
  azure-native:location: WestUS2
  crittercapture:api-certificate-name: api.crittercapture.club-critterc-240904131143
  crittercapture:api-domain: api.crittercapture.club
  crittercapture:api-image: ghcr.io/changesbyjames/crittercapture:main-10774798694-api
  crittercapture:ingest-image: ghcr.io/changesbyjames/crittercapture:main-10774798694-ingest
  crittercapture:image-resize-cdn-url: https://crittercapture.club/cdn-cgi/image
  crittercapture:jwt-secret:
    secure: AAABALRo47EbLSZ++/XslsH1EnlB3vX5iE205SOK4WTv6ElXdOastYUuExCxrhcXOR4JZQJbxHd2cVRfgMhfvxaX5wASDhkPDKlJjbN2tP8cdEKLLyQ5rrabpi4eXLWI9QqU/xmEih8lL0WhXUU+J+NfnwReXC0Bcfn98yUb9nVwM/v/IDTAAFZ9UXleB/oAS0Jrmh5c6fI5rCEeBoWT8w==
  crittercapture:twitch-api-token:
    secure: AAABAEPWRs1YNcZlzxza5RRgZdazpPxQ8SFj6SLA8iEbR1DlfzWCZvoHA00alSq07URn1WoGxjWNtXSidWo=
  crittercapture:twitch-client-id: itag8f5m4r3ynbtrz933d7qh7c6ffq
  crittercapture:twitch-client-secret:
    secure: AAABAG0Qc+H+3ZiC/BAz9AsJRBt8X4J1IJ+CwlpQMoqGGxehsbBxq6vAPwaY+FuEk1y005zygnwBljatENg=
  crittercapture:twitch-feed-key:
    secure: AAABADkxjQzg4f8cClzRfQ2UKueEjyiKlHphid8rn9pW/Zkqv+vNiq+3sE+/e7FbEQI8/TTlnXR7zwbDWQh2vA==
  crittercapture:twitch-username: pollinatorcam
  crittercapture:ui-domain: crittercapture.club
